*** a/.github/workflows/main.yml
--- b/.github/workflows/main.yml
@@
-      - uses: Platane/snk@v3
-        with:
-          github_user_name: Ives Cezar
-          outputs: |
-            dist/github-contribution-grid-snake.svg
-            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
+      - uses: Platane/snk@v3
+        with:
+          github_user_name: ${{ github.actor }}
+          outputs: |
+            dist/github-contribution-grid-snake.svg
+            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
